name: pulseira_sensorial
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Ícones do iOS/Apple
  cupertino_icons: ^1.0.8
  
  # Bibliotecas do nosso Backend e Segurança
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  # Aqui nós liberamos a pasta de imagens para o Flutter ler o fundo.jpg
  assets:
    - assets/images/logo.png
    - assets/images/